const GET_USER = 'GET_USER';
const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
const GET_USER_FAIL = 'GET_USER_FAIL';
const CLEAR_USER = 'CLEAR_USER';
export {GET_USER, GET_USER_SUCCESS, GET_USER_FAIL, CLEAR_USER};
