const GET_NOTIFICATION = 'GET_NOTIFICATION';
const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
const GET_NOTIFICATION_FAIL = 'GET_NOTIFICATION_SUCCESS';
const GET_NOTIFICATION_COUNT_UNREAD = 'GET_NOTIFICATION_COUNT_UNREAD';
const GET_NOTIFICATION_COUNT_UNREAD_SUCCESS =
  'GET_NOTIFICATION_COUNT_UNREAD_SUCCESS';
const GET_NOTIFICATION_COUNT_UNREAD_FAIL = 'GET_NOTIFICATION_COUNT_UNREAD_FAIL';
const MASK_AS_READ = 'MASK_AS_READ';
const MASK_AS_READ_SUCCESS = 'MASK_AS_READ_SUCCESS';
const GET_MORE_NOTIFICATION = 'GET_MORE_NOTIFICATION';
const GET_MORE_NOTIFICATION_SUCCESS = 'GET_MORE_NOTIFICATION_SUCCESS';
const GET_MORE_NOTIFICATION_FAIL = 'GET_MORE_NOTIFICATION_FAIL';

const getNotification = (data: object) => ({
  type: GET_NOTIFICATION,
  payload: data,
});
const getMoreNotification = (data: object) => ({
  type: GET_MORE_NOTIFICATION,
  payload: data,
});
const getCountUnreadNotification = () => ({
  type: GET_NOTIFICATION_COUNT_UNREAD,
});
const maskAsRead = (data: object) => ({
  type: MASK_AS_READ,
  payload: data,
});

export {
  getNotification,
  getCountUnreadNotification,
  maskAsRead,
  getMoreNotification,
  GET_NOTIFICATION,
  GET_NOTIFICATION_SUCCESS,
  GET_NOTIFICATION_FAIL,
  GET_NOTIFICATION_COUNT_UNREAD,
  GET_NOTIFICATION_COUNT_UNREAD_SUCCESS,
  GET_NOTIFICATION_COUNT_UNREAD_FAIL,
  MASK_AS_READ,
  MASK_AS_READ_SUCCESS,
  GET_MORE_NOTIFICATION,
  GET_MORE_NOTIFICATION_SUCCESS,
  GET_MORE_NOTIFICATION_FAIL,
};
